name = "aoe2invitationalladder"
compatibility_date = "2026-05-27"
compatibility_flags = ["nodejs_compat"]


pages_build_output_dir = "dist"

[browser]
binding = "BROWSER"

[[kv_namespaces]]
binding = "aoe2_data"
id = "ee5c521804b846c7a36e5c079c29c719"